### ISSUE TITLE
Create a proper Sign Up

### ISSUE THREAD

**Issue by gary-host-laptop** [thejambi/SkudPaiSho#106]
Hey, the project is awesome and I love the fact that it is open source but the sign in and receive a verification code every time I log in from a different place is quite annoying and it does not make sense if you ask me. The proper way would be to have a button in the nav bar for "Sign in" and another for "Sign up", in the first it should ask for the credentials you want to use and the verification code to prevent spam, and in the latter only your credentials.

**Comment by thejambi** [comment]
Can't be worked on at this time. Will close so the "Issues" list doesn't clog up my head and slow down progress on other things that are more important.
