### ISSUE TITLE
Create a profile page

### ISSUE THREAD

**Issue by gary-host-laptop** [thejambi/SkudPaiSho#107]
It would be awesome if there would be a profile page for users, where one could see the stats of your games, some description box (maybe a profile picture?), and some other stuff, instead of listing everything under the "My Games" button in the landing page.

Lichess does this pretty nicely in my opinion:

![Screenshot from 2021-08-27 19-14-52](https://user-images.githubusercontent.com/63723030/131193883-918cb154-79d5-4ae1-8a6a-1992a3a662ec.png)

I am not asking for something so polished, but anything is better than nothing.

**Comment by thejambi** [comment]
Hopefully I can get to this after Trifle. I have thought about what I'd have it be like.

**Comment by thejambi** [comment]
Please take further discussion about these things to Discord.

**Comment by gary-host-laptop** [comment]
> Please take further discussion about these things to Discord.

Okay, I'll try to go there although I'm not so keen of for privacy reason. Still, I've never seen any project that wants to ask for features in a chat rather than in the repository's issues, doing it othewise doesn't help to have an organized centre of discussion from a technical standpoint, but okay I guess?

**Comment by thejambi** [comment]
Because details will be/have been discussed with Patreon supporters :)
