### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by gary-host-laptop** [thejambi/SkudPaiSho#135]
Right now the repository does not contain any license, which means anyone could grab your source code, use it, don't give credits and you don't have any type of legal support to fight against that. I recommend using the GPLv3 since it is backed by the Free Software Foundation and it can give you a much stronger legal support since there have already been various similar precedents if help is ever needed.

**Comment by thejambi** [comment]
Oh, I thought I had that in, thanks! Should be set now.

**Comment by gary-host-laptop** [comment]
Don't worry about it! 😄
